GET http://localhost:3005/api/persons

###
DELETE http://localhost:3005/api/persons/4

###
POST http://localhost:3005/api/persons
Content-Type: application/json

{
    "name": "Gaurish Kamat",
    "number": "9922339855"
}